apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/kt-cloudnative/springboot_crud_security
  newTag: v1
- name: ghcr.io/le2yeji/springboot_crud_security
  newTag: "20240215090446"
